/* Generated by Configure-Addin.ps1 - do not edit; edit src\commands.js instead.
   ooo-core.js is inlined here because Outlook on the web loads only this file
   for event-based activation and never loads commands.html. */
/*
 * Fill these in AFTER IT completes the Entra app registration and tells you
 * where the add-in will be hosted. Everything else in the add-in reads from here.
 *
 * manifest.xml contains the same placeholders - keep the two in step.
 */
var OooConfig = {
  // Application (client) ID from the Entra app registration.
  clientId: '5173e29d-0a45-45bd-a734-474006421d42',

  // Directory (tenant) ID. 'common' works but pinning the tenant is tighter.
  tenantId: '17f2fc0e-75aa-464d-9428-9811d5baa84e',

  // HTTPS origin the add-in is served from, no trailing slash,
  // e.g. https://dashtech.github.io/signature-ooo
  hostUrl: 'https://ravee-acharya.github.io/outlook-ooo-signature',

  // Must exactly match a redirect URI registered on the app, character for
  // character. auth-end.html sits in src/ alongside this file - omitting that
  // segment yields a 404 that only surfaces mid sign-in.
  get redirectUri() { return this.hostUrl + '/src/auth-end.html'; },

  // Read-only, calendar-only. User.Read is just for showing whose account is linked.
  scopes: ['User.Read', 'Calendars.Read'],

  // Defaults for a new user; changeable in the task pane.
  defaults: {
    months: 3,
    timeZoneLabel: 'IST',
    timeZoneId: 'India Standard Time',
    heading: 'Upcoming Out of Office Days',
    color: '#FF0000'
  }
};

if (typeof module === 'object' && module.exports) { module.exports = OooConfig; }

/*
 * Shared out-of-office logic for the Outlook add-in.
 *
 * This is a direct port of OooCore.ps1 and must stay behaviourally identical to
 * it - test/test-core.js runs the same fixtures as the PowerShell test suite.
 *
 * Loaded both in the browser (task pane + event runtime) and in Node for tests.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) { module.exports = factory(); }
  else { root.OooCore = factory(); }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
                'July', 'August', 'September', 'October', 'November', 'December'];

  var DEFAULTS = {
    heading: 'Upcoming Out of Office Days',
    color: '#FF0000',
    fontFamily: 'Calibri,Arial,sans-serif',
    fontSize: '11pt',
    timeZoneLabel: 'IST',
    months: 3,
    noonCutoff: 12
  };

  // Subjects/categories that mean "not at work". 'wfh' is deliberately absent:
  // working from home still means available.
  var KEYWORDS = ['holiday', 'leave', 'pto', 'vacation', 'out of office', 'ooo',
                  'day off', 'comp off', 'sick', 'festival'];
  var CATEGORY_MATCHES = ['holiday', 'out of office', 'ooo', 'leave'];

  // ---------------------------------------------------------------- dates
  function dateOnly(d) { return new Date(d.getFullYear(), d.getMonth(), d.getDate()); }
  function addDays(d, n) { var x = new Date(d.getTime()); x.setDate(x.getDate() + n); return x; }

  function toISO(d) {
    return d.getFullYear() + '-' +
           ('0' + (d.getMonth() + 1)).slice(-2) + '-' +
           ('0' + d.getDate()).slice(-2);
  }

  function parseISO(s) {
    var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s);
    return m ? new Date(+m[1], +m[2] - 1, +m[3]) : null;
  }

  // Clamps to the last day of the target month, matching .NET's AddMonths
  // (31 Aug + 3 months = 30 Nov, not 1 Dec).
  function addMonths(d, n) {
    var day = d.getDate();
    var x = new Date(d.getFullYear(), d.getMonth() + n, 1);
    var dim = new Date(x.getFullYear(), x.getMonth() + 1, 0).getDate();
    x.setDate(Math.min(day, dim));
    return x;
  }

  // Graph returns "2026-09-04T10:00:00.0000000" with no zone marker; combined
  // with the Prefer: outlook.timezone header these are already wall-clock times
  // in the requested zone, so they must be read literally rather than as UTC.
  function parseGraphDateTime(s) {
    var m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})/.exec(String(s));
    return m ? new Date(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6]) : null;
  }

  // ---------------------------------------------------------------- formatting
  function ordinal(n) {
    if (n === 11 || n === 12 || n === 13) { return 'th'; }
    switch (n % 10) {
      case 1: return 'st';
      case 2: return 'nd';
      case 3: return 'rd';
      default: return 'th';
    }
  }

  function formatDay(d) {
    return MONTHS[d.getMonth()] + ' ' + d.getDate() + '<sup>' + ordinal(d.getDate()) + '</sup>';
  }

  function formatTime(d) {
    var h = d.getHours(), m = d.getMinutes();
    var ap = h >= 12 ? 'PM' : 'AM';
    var h12 = h % 12; if (h12 === 0) { h12 = 12; }
    return m === 0 ? (h12 + ' ' + ap) : (h12 + ':' + ('0' + m).slice(-2) + ' ' + ap);
  }

  function escapeHtml(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  // ---------------------------------------------------------------- event -> days
  //
  // All-day events end at 00:00 on the day AFTER the last day off, so the end
  // is pulled back a day.
  //
  // Timed events need both edges trimmed:
  //   - ending before noon on a later day means you are back that morning, so
  //     that day is dropped ("4 Sep 10:00 -> 7 Sep 09:00" is the 4th to 6th);
  //   - starting at or after noon costs only part of the first day, so it gets
  //     an "after 6 PM IST" note and later stands as its own line.
  function getEventDays(start, end, isAllDay, opts) {
    opts = opts || {};
    var tzLabel = opts.timeZoneLabel || DEFAULTS.timeZoneLabel;
    var cutoff = opts.noonCutoff == null ? DEFAULTS.noonCutoff : opts.noonCutoff;

    var startDay = dateOnly(start);
    var note = '';
    var lastDay;

    if (isAllDay) {
      lastDay = dateOnly(end);
      if (end.getHours() === 0 && end.getMinutes() === 0 && end.getSeconds() === 0) {
        lastDay = addDays(lastDay, -1);
      }
    } else {
      lastDay = dateOnly(end);
      if (lastDay.getTime() > startDay.getTime() && end.getHours() < cutoff) {
        lastDay = addDays(lastDay, -1);
      }
      if (start.getHours() >= cutoff) {
        note = 'after ' + formatTime(start) + ' ' + tzLabel;
      }
    }
    if (lastDay.getTime() < startDay.getTime()) { lastDay = startDay; }

    var out = {};
    for (var d = startDay; d.getTime() <= lastDay.getTime(); d = addDays(d, 1)) {
      out[toISO(d)] = (d.getTime() === startDay.getTime()) ? note : '';
    }
    return out;
  }

  // A day's value is either a plain string (a partial-day note, e.g.
  // "after 6 PM IST") or an object { note, label }. The label carries a public
  // holiday's name so the recipient can tell a company holiday from personal
  // leave. Strings are kept for the common case so nothing about the previous
  // stored format or output changes.
  function normDay(v) {
    if (v == null) { return { note: '', label: '' }; }
    if (typeof v === 'string') { return { note: v, label: '' }; }
    return { note: v.note || '', label: v.label || '' };
  }

  // Merges two entries for the same date. A whole day always beats a
  // partial-day note, and a holiday name survives either way - a day that is
  // both personal leave and a public holiday should still name the holiday.
  function combineEntry(a, b) {
    var A = normDay(a), B = normDay(b);
    var note = (A.note === '' || B.note === '') ? '' : A.note;
    var label = A.label || B.label;
    return label ? { note: note, label: label } : note;
  }

  // Folds one event's days into the running set, clipped to the window.
  function mergeDays(target, newDays, from, to) {
    Object.keys(newDays).forEach(function (k) {
      var d = parseISO(k);
      if (!d || d.getTime() < from.getTime() || d.getTime() > to.getTime()) { return; }
      target[k] = Object.prototype.hasOwnProperty.call(target, k)
        ? combineEntry(target[k], newDays[k])
        : newDays[k];
    });
    return target;
  }

  function buildRuns(days) {
    var keys = Object.keys(days).sort();
    var runs = [], cur = null;
    keys.forEach(function (k) {
      var d = parseISO(k), e = normDay(days[k]);
      // Consecutive whole days merge only when they carry the same label, so a
      // two-day holiday stays one line but a holiday never absorbs the day
      // beside it.
      if (cur && cur.note === '' && e.note === '' && cur.label === e.label &&
          toISO(addDays(cur.end, 1)) === k) {
        cur.end = d;
        return;
      }
      if (cur) { runs.push(cur); }
      cur = { start: d, end: d, note: e.note, label: e.label };
    });
    if (cur) { runs.push(cur); }
    return runs;
  }

  function renderBlock(runs, opts) {
    if (!runs || !runs.length) { return ''; }
    opts = opts || {};
    var color = opts.color || DEFAULTS.color;
    var heading = opts.heading || DEFAULTS.heading;
    var font = opts.fontFamily || DEFAULTS.fontFamily;
    var size = opts.fontSize || DEFAULTS.fontSize;
    var line = 'margin:0;padding:0;color:' + color + ';font-weight:bold;font-family:' +
               font + ';font-size:' + size + ';';

    var out = [];
    out.push('<div style="margin:10px 0;font-family:' + font + ';font-size:' + size + ';">');
    out.push('<p style="' + line + '"><u>' + escapeHtml(heading) + '</u></p>');
    runs.forEach(function (r) {
      var text = (r.start.getTime() === r.end.getTime())
        ? formatDay(r.start)
        : formatDay(r.start) + ' &#8211; ' + formatDay(r.end);
      if (r.note) { text += ' ' + escapeHtml(r.note); }
      if (r.label) { text += ' (' + escapeHtml(r.label) + ')'; }
      out.push('<p style="' + line + '">' + text + '</p>');
    });
    out.push('</div>');
    return out.join('\n');
  }

  // ---------------------------------------------------------------- filtering
  function isOooEvent(ev) {
    if (ev.isCancelled) { return false; }
    if (ev.showAs === 'oof') { return true; }
    var subject = String(ev.subject || '').toLowerCase();
    var cats = (ev.categories || []).join(' ').toLowerCase();
    var i;
    for (i = 0; i < CATEGORY_MATCHES.length; i++) {
      if (cats.indexOf(CATEGORY_MATCHES[i]) !== -1) { return true; }
    }
    for (i = 0; i < KEYWORDS.length; i++) {
      if (subject.indexOf(KEYWORDS[i]) !== -1) { return true; }
    }
    return false;
  }

  // ---------------------------------------------------------------- pipelines
  // Graph events -> { 'yyyy-MM-dd': note }. Stored rather than rendered HTML so
  // the compose-time handler can drop expired days without a network call.
  function daysFromEvents(events, opts) {
    opts = opts || {};
    var today = opts.today ? dateOnly(opts.today) : dateOnly(new Date());
    var windowEnd = addMonths(today, opts.months == null ? DEFAULTS.months : opts.months);
    var days = {};

    (events || []).forEach(function (ev) {
      if (!isOooEvent(ev)) { return; }
      var s = parseGraphDateTime(ev.start && ev.start.dateTime);
      var e = parseGraphDateTime(ev.end && ev.end.dateTime);
      if (!s || !e) { return; }
      mergeDays(days, getEventDays(s, e, !!ev.isAllDay, opts), today, windowEnd);
    });
    return days;
  }

  // Re-clips a stored day map to today's window, so a signature inserted weeks
  // after the last refresh still drops dates that have since passed.
  function clipDays(days, opts) {
    opts = opts || {};
    var today = opts.today ? dateOnly(opts.today) : dateOnly(new Date());
    var windowEnd = addMonths(today, opts.months == null ? DEFAULTS.months : opts.months);
    var out = {};
    Object.keys(days || {}).forEach(function (k) {
      var d = parseISO(k);
      if (!d || d.getTime() < today.getTime() || d.getTime() > windowEnd.getTime()) { return; }
      out[k] = days[k];
    });
    return out;
  }

  // Company-wide holidays published centrally alongside the add-in, so one
  // person can maintain them for everybody. Same shape as the CSV the desktop
  // tool uses: start, optional end (inclusive), optional note.
  function daysFromHolidays(list, opts) {
    opts = opts || {};
    var today = opts.today ? dateOnly(opts.today) : dateOnly(new Date());
    var windowEnd = addMonths(today, opts.months == null ? DEFAULTS.months : opts.months);
    var days = {};

    (list || []).forEach(function (h) {
      if (!h || !h.start) { return; }
      var s = parseISO(h.start);
      if (!s) { return; }
      var e = h.end ? parseISO(h.end) : s;
      if (!e) { e = s; }
      if (e.getTime() < s.getTime()) { var t = s; s = e; e = t; }

      var note = String(h.note || '').trim();
      var label = String(h.name || '').trim();
      var out = {};
      for (var d = s; d.getTime() <= e.getTime(); d = addDays(d, 1)) {
        // The label goes on every day of the range so the whole range merges
        // into a single line; the note applies to the first day only.
        var dayNote = (d.getTime() === s.getTime()) ? note : '';
        out[toISO(d)] = label ? { note: dayNote, label: label } : dayNote;
      }
      mergeDays(days, out, today, windowEnd);
    });
    return days;
  }

  // Combines personal leave with company holidays. Both are already clipped to
  // the window, so no re-clipping here. A whole day always beats a partial-day
  // note for the same date, whichever side it came from.
  function unionDays(a, b) {
    var out = {};
    Object.keys(a || {}).forEach(function (k) { out[k] = a[k]; });
    Object.keys(b || {}).forEach(function (k) {
      out[k] = Object.prototype.hasOwnProperty.call(out, k)
        ? combineEntry(out[k], b[k])
        : b[k];
    });
    return out;
  }

  function blockFromDays(days, opts) {
    return renderBlock(buildRuns(clipDays(days, opts)), opts);
  }

  return {
    DEFAULTS: DEFAULTS,
    KEYWORDS: KEYWORDS,
    dateOnly: dateOnly,
    addDays: addDays,
    addMonths: addMonths,
    toISO: toISO,
    parseISO: parseISO,
    parseGraphDateTime: parseGraphDateTime,
    ordinal: ordinal,
    formatDay: formatDay,
    formatTime: formatTime,
    getEventDays: getEventDays,
    mergeDays: mergeDays,
    buildRuns: buildRuns,
    renderBlock: renderBlock,
    isOooEvent: isOooEvent,
    daysFromEvents: daysFromEvents,
    clipDays: clipDays,
    normDay: normDay,
    daysFromHolidays: daysFromHolidays,
    unionDays: unionDays,
    blockFromDays: blockFromDays
  };
}));

/*
 * Microsoft Graph calls. Read-only: calendarView and /me, nothing else.
 */
var OooGraph = (function () {
  'use strict';

  var BASE = 'https://graph.microsoft.com/v1.0';

  function pad(n) { return ('0' + n).slice(-2); }

  // Local wall-clock, no zone suffix - paired with the Prefer header below so
  // Graph interprets and returns everything in the user's own time zone.
  function graphLocal(d) {
    return d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate()) +
           'T' + pad(d.getHours()) + ':' + pad(d.getMinutes()) + ':' + pad(d.getSeconds());
  }

  async function call(url, token, timeZoneId) {
    var headers = { Authorization: 'Bearer ' + token };
    if (timeZoneId) { headers.Prefer = 'outlook.timezone="' + timeZoneId + '"'; }

    var res = await fetch(url, { headers: headers });
    if (!res.ok) {
      var detail = '';
      try {
        var body = await res.json();
        detail = (body.error && body.error.message) ? ': ' + body.error.message : '';
      } catch (e) { /* non-JSON error body */ }
      throw new Error('Graph ' + res.status + detail);
    }
    return res.json();
  }

  async function getMe(token) {
    var me = await call(BASE + '/me?$select=displayName,userPrincipalName,mail', token, null);
    var addr = me.mail || me.userPrincipalName;
    return { name: me.displayName || '', address: addr || '', label: me.displayName ? (me.displayName + ' <' + addr + '>') : addr };
  }

  /**
   * Events overlapping the window. Starts 90 days early so multi-day leave that
   * began before today is still caught and clipped, matching the desktop tool.
   */
  async function getCalendarEvents(token, from, to, timeZoneId) {
    var url = BASE + '/me/calendarView' +
      '?startDateTime=' + encodeURIComponent(graphLocal(OooCore.addDays(from, -90))) +
      '&endDateTime=' + encodeURIComponent(graphLocal(OooCore.addDays(to, 1))) +
      '&$select=subject,start,end,isAllDay,showAs,categories,isCancelled' +
      '&$top=200';

    var events = [];
    var guard = 0;
    while (url && guard++ < 50) {
      var page = await call(url, token, timeZoneId);
      events = events.concat(page.value || []);
      url = page['@odata.nextLink'];
    }
    return events;
  }

  return { getMe: getMe, getCalendarEvents: getCalendarEvents };
}());

/*
 * Company-wide holidays, published once and applied to everyone.
 *
 * The list lives at <host>/holidays.json, which the app owner edits directly on
 * GitHub. It is fetched same-origin, so no CORS and no credentials are involved,
 * and it holds nothing sensitive - just dates.
 *
 * The file carries one list per region (India, United States, ...) and each
 * user picks exactly one. Two regions are never combined: someone in the India
 * office should not advertise US federal holidays, or the reverse.
 *
 * An older flat file - { "holidays": [...] } with no regions - is still
 * accepted and treated as a single unnamed region, so a cached copy from before
 * this change keeps working.
 *
 * Every consumer caches the parsed result in roaming settings, so the list keeps
 * working offline and inside the compose handler's tight time budget.
 */
var OooShared = (function () {
  'use strict';

  var CACHE_KEY = 'oooSharedHolidays';
  var CACHE_AT_KEY = 'oooSharedHolidaysAt';
  var LEGACY_KEY = '_all';

  // Array.isArray rather than `instanceof Array`: the latter is false for an
  // array created in a different realm, which silently discarded the whole list
  // in one earlier test harness.
  function isArr(v) { return Object.prototype.toString.call(v) === '[object Array]'; }

  function url() {
    var base = (typeof OooConfig !== 'undefined' && OooConfig.hostUrl) ? OooConfig.hostUrl : '';
    // Bucketed by the hour: fresh enough for a list that changes a few times a
    // year, without defeating caching on every single compose.
    var bucket = Math.floor(Date.now() / 3600000);
    return base + '/holidays.json?h=' + bucket;
  }

  /**
   * Accepts either shape and always returns
   *   { updated, defaultRegion, regions: [{ key, label, holidays }] }
   * or null when there is nothing usable.
   */
  function normalise(json) {
    if (!json) { return null; }

    if (isArr(json.regions)) {
      var regions = [];
      json.regions.forEach(function (r) {
        if (!r || !r.key || !isArr(r.holidays)) { return; }
        regions.push({
          key: String(r.key),
          label: String(r.label || r.key),
          holidays: r.holidays
        });
      });
      if (!regions.length) { return null; }
      return {
        updated: json.updated || '',
        defaultRegion: json.defaultRegion || regions[0].key,
        regions: regions
      };
    }

    // Legacy flat file.
    if (isArr(json.holidays)) {
      return {
        updated: json.updated || '',
        defaultRegion: LEGACY_KEY,
        regions: [{ key: LEGACY_KEY, label: 'Company holidays', holidays: json.holidays }]
      };
    }
    return null;
  }

  /**
   * @returns {Promise<object|null>} normalised list, or null on any failure
   */
  function fetchList() {
    if (typeof fetch !== 'function') { return Promise.resolve(null); }
    return fetch(url())
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (j) { return normalise(j); })
      .catch(function () { return null; });
  }

  function readCache(rs) {
    try {
      var raw = rs.get(CACHE_KEY);
      if (!raw) { return null; }
      return normalise(JSON.parse(raw));
    } catch (e) { return null; }
  }

  function writeCache(rs, list) {
    try {
      rs.set(CACHE_KEY, JSON.stringify(list));
      rs.set(CACHE_AT_KEY, new Date().toISOString());
      return true;
    } catch (e) { return false; }
  }

  function regionsOf(list) {
    return (list && isArr(list.regions)) ? list.regions : [];
  }

  /**
   * The user's chosen region, falling back to the file's default and then to the
   * first one. Returns null when the chosen key no longer exists and there is no
   * sensible fallback - better to show nothing than another region's holidays.
   */
  function pickRegion(list, regionKey) {
    var regions = regionsOf(list);
    if (!regions.length) { return null; }

    var i;
    if (regionKey) {
      for (i = 0; i < regions.length; i++) {
        if (regions[i].key === regionKey) { return regions[i]; }
      }
      // A key that no longer exists means the published file changed under the
      // user. Fall through to the default rather than guessing.
    }
    var def = list.defaultRegion;
    if (def) {
      for (i = 0; i < regions.length; i++) {
        if (regions[i].key === def) { return regions[i]; }
      }
    }
    return regions[0];
  }

  // Day map for exactly one region. Never merges two regions.
  function toDays(list, opts, regionKey) {
    var region = pickRegion(list, regionKey);
    if (!region) { return {}; }
    return OooCore.daysFromHolidays(region.holidays, opts);
  }

  return {
    CACHE_KEY: CACHE_KEY,
    CACHE_AT_KEY: CACHE_AT_KEY,
    LEGACY_KEY: LEGACY_KEY,
    normalise: normalise,
    fetchList: fetchList,
    readCache: readCache,
    writeCache: writeCache,
    regionsOf: regionsOf,
    pickRegion: pickRegion,
    toDays: toDays
  };
}());

/*
 * Event-based runtime: runs on every new message compose and writes the
 * signature, with the out-of-office block on top.
 *
 * Hard rule for this file: NEVER prompt for sign-in, and never let anything
 * block indefinitely. Outlook gives a compose handler only a few seconds before
 * it kills the runtime, and a blocked handler means the user gets no signature
 * at all.
 *
 * It does attempt one time-boxed calendar refresh so newly added or removed
 * out-of-office dates appear without the user opening the task pane. That
 * refresh is strictly optional: it uses a silently cached token only, is capped
 * by REFRESH_BUDGET_MS, and on any failure or timeout the handler falls straight
 * back to the dates already in roaming settings. Worst case is identical to
 * having no refresh at all.
 *
 * Dates are stored rather than rendered HTML, so days that have passed since the
 * last refresh are dropped here, offline, at the moment the mail is composed.
 *
 * This runtime has no visible console, so every outcome is recorded back into
 * roaming settings under 'oooLastEvent' and surfaced by the task pane. Without
 * that, a failure here is completely silent.
 */

var STORE = {
  days: 'oooDays',
  signature: 'signatureHtml',
  options: 'oooOptions',
  enabled: 'oooEnabled',
  refreshed: 'oooRefreshed',
  lastEvent: 'oooLastEvent',
  useShared: 'oooUseShared',
  activated: 'oooActivated',
  region: 'oooRegion',
  account: 'oooAccount'
};

// How long the optional calendar refresh may take before we give up and use the
// stored dates. Outlook's compose budget is a few seconds and the signature
// matters more than its freshness, so this stays well under the 4s guard below.
var REFRESH_BUDGET_MS = 2500;

function withTimeout(promise, ms, fallback) {
  return new Promise(function (resolve) {
    var settled = false;
    var timer = setTimeout(function () {
      if (!settled) { settled = true; resolve(fallback); }
    }, ms);
    promise.then(function (v) {
      if (!settled) { settled = true; clearTimeout(timer); resolve(v); }
    }, function () {
      if (!settled) { settled = true; clearTimeout(timer); resolve(fallback); }
    });
  });
}

// Why the last refresh attempt did or did not happen, for the diagnostic line.
var refreshWhy = 'not-attempted';

// Silent only - never interactive. This runtime shares browser storage with the
// task pane (both are frames inside Outlook), and the pane imports the sign-in
// dialog's MSAL cache into it, so the cached account is visible here. If MSAL is
// absent (the JavaScript-only runtime on classic Windows) or nothing is cached,
// we simply skip the refresh.
function getSilentToken() {
  return new Promise(function (resolve) {
    if (typeof msal === 'undefined' || typeof OooConfig === 'undefined') {
      refreshWhy = 'msal-unavailable'; resolve(null); return;
    }
    try {
      var pca = new msal.PublicClientApplication({
        auth: {
          clientId: OooConfig.clientId,
          authority: 'https://login.microsoftonline.com/' + (OooConfig.tenantId || 'common'),
          redirectUri: OooConfig.redirectUri,
          navigateToLoginRequestUrl: false
        },
        cache: { cacheLocation: 'localStorage' },
        // A hidden-iframe renewal that is going to fail should not outlive the
        // compose budget by much.
        system: { iframeHashTimeout: 2000 }
      });
      var ready = pca.initialize ? pca.initialize() : Promise.resolve();
      ready.then(function () {
        var acct = pca.getActiveAccount() || (pca.getAllAccounts() || [])[0];
        if (!acct) { refreshWhy = 'no-cached-account'; return null; }
        return pca.acquireTokenSilent({ scopes: OooConfig.scopes, account: acct });
      }).then(function (r) {
        resolve(r && r.accessToken ? r.accessToken : null);
      }).catch(function (e) {
        refreshWhy = 'silent-failed:' + ((e && (e.errorCode || e.name)) || 'unknown');
        resolve(null);
      });
    } catch (e) { refreshWhy = 'msal-error'; resolve(null); }
  });
}

// Returns a fresh day map, or null if anything at all gets in the way.
function refreshDays(options) {
  if (typeof OooGraph === 'undefined' || typeof OooCore === 'undefined') {
    return Promise.resolve(null);
  }
  var months = options.months || 3;
  return getSilentToken().then(function (token) {
    if (!token) { return null; }
    var today = OooCore.dateOnly(new Date());
    var windowEnd = OooCore.addMonths(today, months);
    var tz = (typeof OooConfig !== 'undefined' && OooConfig.defaults && OooConfig.defaults.timeZoneId)
      ? OooConfig.defaults.timeZoneId : 'India Standard Time';
    refreshWhy = 'graph-pending';
    return OooGraph.getCalendarEvents(token, today, windowEnd, tz).then(function (events) {
      refreshWhy = 'ok';
      return OooCore.daysFromEvents(events, {
        today: today,
        months: months,
        timeZoneLabel: options.timeZoneLabel || 'IST'
      });
    });
  }).catch(function () {
    if (refreshWhy === 'graph-pending') { refreshWhy = 'graph-failed'; }
    return null;
  });
}

// Office.onReady must be called in an event-based runtime; without it
// Office.context can still be uninitialised when the handler is invoked.
var officeReady = false;
if (typeof Office !== 'undefined' && typeof Office.onReady === 'function') {
  Office.onReady(function () { officeReady = true; });
}

function ready() {
  return new Promise(function (resolve) {
    if (officeReady) { resolve(); return; }
    if (typeof Office !== 'undefined' && typeof Office.onReady === 'function') {
      Office.onReady(function () { officeReady = true; resolve(); });
    } else {
      resolve();
    }
  });
}

// Whether this mailbox has ever completed a sign-in in the task pane.
//
// This gates the entire handler. The company holiday list is a public static
// file needing no authentication, so without this check a user who never signed
// in would still get holidays injected - and because their own signature is
// unset, setSignatureAsync would REPLACE their normal Outlook signature with a
// bare holiday block.
//
// The explicit flag is authoritative; the older signals are honoured so people
// already using the add-in are not forced to sign in again.
function isActivated(rs) {
  var flag = rs.get(STORE.activated);
  if (flag === true) { return true; }
  if (flag === false) { return false; }
  return !!(rs.get(STORE.refreshed) || rs.get(STORE.account));
}

function readSettings() {
  var rs = Office.context.roamingSettings;
  var days = {}, options = {};
  try { days = JSON.parse(rs.get(STORE.days) || '{}'); } catch (e) { days = {}; }
  try { options = JSON.parse(rs.get(STORE.options) || '{}'); } catch (e) { options = {}; }
  return {
    days: days,
    options: options,
    signature: rs.get(STORE.signature) || '',
    enabled: rs.get(STORE.enabled) !== false,
    // Company holidays are on unless the user has explicitly opted out.
    useShared: rs.get(STORE.useShared) !== false,
    region: rs.get(STORE.region) || '',
    sharedCache: (typeof OooShared !== 'undefined') ? OooShared.readCache(rs) : null
  };
}

// Personal leave plus company holidays, honouring the user's opt-out.
function combinedDays(s) {
  if (!s.useShared || typeof OooShared === 'undefined' || !s.sharedCache) {
    return s.days;
  }
  try {
    var sharedDays = OooShared.toDays(s.sharedCache, s.options, s.region);
    return OooCore.unionDays(s.days, sharedDays);
  } catch (e) {
    return s.days;   // a bad shared list must never cost the user their own dates
  }
}

// Fire-and-forget: never let recording a diagnostic delay event.completed().
function note(outcome, detail) {
  try {
    var rs = Office.context.roamingSettings;
    rs.set(STORE.lastEvent, JSON.stringify({
      at: new Date().toISOString(),
      outcome: outcome,
      detail: detail || ''
    }));
    rs.saveAsync(function () { /* ignore */ });
  } catch (e) { /* diagnostics must never break the handler */ }
}

function buildSignatureHtml(s) {
  if (!s.enabled && !s.signature) { return null; }
  var block = '';
  if (s.enabled) {
    try {
      block = OooCore.blockFromDays(combinedDays(s), s.options) || '';
    } catch (e) {
      block = '';   // never let a rendering fault cost the user their signature
    }
  }
  return (block ? block + s.signature : s.signature) || null;
}

function onNewMessageComposeHandler(event) {
  var done = false;
  function finish() {
    if (done) { return; }
    done = true;
    try { event.completed(); } catch (e) { /* already completed */ }
  }

  // Belt and braces: if anything stalls, still release the compose window.
  var guard = setTimeout(function () { note('timeout', 'handler exceeded 4s'); finish(); }, 4000);

  ready().then(function () {
    try {
      if (typeof OooCore === 'undefined') {
        note('error', 'OooCore not loaded');
        clearTimeout(guard); finish(); return;
      }
      if (!Office.context || !Office.context.roamingSettings) {
        note('error', 'roamingSettings unavailable');
        clearTimeout(guard); finish(); return;
      }

      if (!isActivated(Office.context.roamingSettings)) {
        // Not signed in: touch nothing at all, so Outlook's own signature
        // behaviour is left exactly as it was.
        note('not-activated', 'user has not signed in to the add-in');
        clearTimeout(guard); finish(); return;
      }

      var s = readSettings();
      refreshWhy = 'timed-out';

      // Optional, time-boxed. Null means "use what we already have".
      var work = Promise.all([
        refreshDays(s.options),
        (typeof OooShared !== 'undefined') ? OooShared.fetchList() : Promise.resolve(null)
      ]);

      withTimeout(work, REFRESH_BUDGET_MS, [null, null]).then(function (both) {
        var freshDays = both && both[0];
        var freshShared = both && both[1];

        if (freshShared && typeof OooShared !== 'undefined') {
          s.sharedCache = freshShared;
          try { OooShared.writeCache(Office.context.roamingSettings, freshShared); } catch (e) { }
        }

        var refreshed = false;
        if (freshDays) {
          s.days = freshDays;
          refreshed = true;
          try {
            var rs = Office.context.roamingSettings;
            rs.set(STORE.days, JSON.stringify(freshDays));
            rs.set(STORE.refreshed, new Date().toISOString());
            rs.saveAsync(function () { /* best effort - must not gate the signature */ });
          } catch (e) { /* ignore */ }
        }

        var dayCount = Object.keys(combinedDays(s) || {}).length;
        var html = buildSignatureHtml(s);

        if (!html) {
          note('nothing-to-insert',
               'days=' + dayCount + ' enabled=' + s.enabled + ' sigLen=' + s.signature.length +
               ' refreshed=' + refreshed + (refreshed ? '' : ' (' + refreshWhy + ')'));
          clearTimeout(guard); finish(); return;
        }

        var item = Office.context.mailbox && Office.context.mailbox.item;
        if (!item || !item.body || typeof item.body.setSignatureAsync !== 'function') {
          note('error', 'setSignatureAsync unavailable');
          clearTimeout(guard); finish(); return;
        }

        item.body.setSignatureAsync(
          html,
          { coercionType: Office.CoercionType.Html },
          function (res) {
            clearTimeout(guard);
            if (res && res.status === Office.AsyncResultStatus.Failed) {
              note('setSignature-failed',
                   (res.error && res.error.message) || 'unknown');
            } else {
              note('inserted',
                   'days=' + dayCount + ' htmlLen=' + html.length +
                   ' refreshed=' + refreshed + (refreshed ? '' : ' (' + refreshWhy + ')'));
            }
            finish();
          }
        );
      });
    } catch (e) {
      note('exception', (e && e.message) ? e.message : String(e));
      clearTimeout(guard);
      finish();
    }
  }).catch(function (e) {
    note('exception', 'ready() failed: ' + ((e && e.message) || String(e)));
    clearTimeout(guard);
    finish();
  });
}

// Outlook on Windows (classic) uses this association; OWA and new Outlook pick
// the function up from the manifest's FunctionName.
if (typeof Office !== 'undefined' && Office.actions && Office.actions.associate) {
  Office.actions.associate('onNewMessageComposeHandler', onNewMessageComposeHandler);
}
